# Generated by Django 3.1.5 on 2021-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.ManyToManyField(blank=True, related_name='item', to='auctions.Listing'),
        ),
    ]
